version: '2'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: express
      POSTGRES_DB: express
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
